### PR TITLE
WIP on refactoring the state machine + dedup logic

### PR DESCRIPTION
**Pull request by alsuren**
I have refactored the flow of information to go:

sensors -> status_helpers -> teapot_state -> server_communicator

so that the Fysom state transition callbacks in teabot_state drive all server communication. This wasn't strictly necessary, but having the state transition triggers and side-effects specified in the same place is quite a common pattern, because it puts the state machine business logic in one place, where it could be automatically extracted and put on a state transition diagram for visual inspection. We could also make server_communicator._queue_brewed_update() an explicit onenter:FULL_TEAPOT callback, rather than a hidden if statement in send_status_update().

I now need to write a recent_empty_scales_periods() function (will require a bit more jiggery-pokery to allow my test fixtures to fuck about with the timestamps on readings, and while I'm there, I will probably want to write a signal handler that will dump the last 30 minutes' data to a fake readings fixture file.

Once we have recent_empty_scales_periods(), we can kill off:
```
            if self.new_teapot_is_not_duplicate():
                state_machine.temp_rising_weight_above_full()
            else:
                # This makes the teapot state be GOOD_TEAPOT and we don't
                # have to worry about duplicate new teapot alerts
                state_machine.weight_above_empty_below_full()
```
and replace it with a "last_preparation_period" variable, and only report FULL_TEAPOT if the most recent empty scales period longer than 2 minutes is more recent than "last_preparation_period". This should get rid of the 40-minute re-reporting bug once and for all.

I know that I should really be doing this more iteratively, so I will probably cherry-pick the recent_empty_scales_periods()+new_teapot_is_not_duplicate()-killing change out into its own PR and test that on the raspberry pi first.

### CODE REVIEW

**Comment by AaronKalair** [comment]
Some PEP 8 things but 🐳

**Comment by alsuren** [comment]
I think I want to fix the dedup thing before I merge this.

**Comment by alsuren** [comment]
Force-pushed to resolve the merge conflict.

That's all of the changes that I wanted to get written in terms of functionality. Let's test it tomorrow and see how well it works in practice, then we can start killing off dead code + renaming FSM events to make more sense.

**Comment by AaronKalair** [comment]
Looks good to me, how did the testing go? Happy for me to merge this?

**Comment by alsuren** [comment]
For some reason, we didn't get any notifications in the teapot room, but the dashboard updated correctly. I should probably check the server logs to find out whether we ever actually attempted the announcement.

**Comment by alsuren** [comment]
Also, Will Black managed to make a teapot in 1 minute and 12 seconds, so we might want to reduce our required emptiness period to 1 minute.

**Comment by AaronKalair** [comment]
I'm seeing these exceptions in Rollbar - 

```Traceback (most recent call last):
  File "teabot/worker.py", line 92, in <module>
    do_work()
  File "teabot/worker.py", line 86, in do_work
    last_preparation_period)
  File "/home/pi/Teabot/teabot/status_helpers.py", line 241, in get_teapot_status
    raise Exception("None of the expected conditions were satisfied")
Exception: None of the expected conditions were satisfied```

**Comment by alsuren** [comment]
I will try to remember to do a git pull, and actually run the calibration script when I get in tomorrow morning.

Next time a "None of the expected conditions were satisfied" exception happens: give me the timestamp, and I will try to extract the fixture file from the pi. If you have access to the values of all variables in local scope, we can probably work out what the missing elif statement is from that, and save ourselves a job.

**Comment by AaronKalair** [comment]
Yep, we have access to the variables I can show you tomorrow

**Pull request merged**
